#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : irrlicht
Version  : 1.8.4
Release  : 17
URL      : https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip
Source0  : https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip
Summary  : Open source realtime 3D engine
Group    : Development/Tools
License  : IJG Libpng Zlib bzip2-1.0.5 bzip2-1.0.6
Requires: irrlicht-lib = %{version}-%{release}
Requires: irrlicht-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-scons
BuildRequires : libpng-dev
BuildRequires : mesa-dev
BuildRequires : pkgconfig(libjpeg)
Patch1: build.patch
Patch2: build-Makefile-system-zlib-and-libpng.patch
Patch3: build-Makefile-system-libjpeg.patch
Patch4: 0001-Fix-build-with-glibc-2.32.patch

%description
The Irrlicht Engine is an open source realtime 3D engine written in C++. It is
cross-platform, using D3D, OpenGL and its own software renderers. OpenGL-ES2
and WebGL renderers are also in development.

%package dev
Summary: dev components for the irrlicht package.
Group: Development
Requires: irrlicht-lib = %{version}-%{release}
Provides: irrlicht-devel = %{version}-%{release}
Requires: irrlicht = %{version}-%{release}

%description dev
dev components for the irrlicht package.


%package lib
Summary: lib components for the irrlicht package.
Group: Libraries
Requires: irrlicht-license = %{version}-%{release}

%description lib
lib components for the irrlicht package.


%package license
Summary: license components for the irrlicht package.
Group: Default

%description license
license components for the irrlicht package.


%prep
%setup -q -n irrlicht-1.8.4
cd %{_builddir}/irrlicht-1.8.4
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1622175095
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto -std=gnu++98"
pushd source/Irrlicht
make  %{?_smp_mflags}
popd


%install
export SOURCE_DATE_EPOCH=1622175095
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/irrlicht
cp %{_builddir}/irrlicht-1.8.4/doc/bzip2-license.txt %{buildroot}/usr/share/package-licenses/irrlicht/d964dbe91cbf7511e4f1857db9e99fdaf6658055
cp %{_builddir}/irrlicht-1.8.4/doc/irrlicht-license.txt %{buildroot}/usr/share/package-licenses/irrlicht/bcbd5fcde0d5d5a7a0e6729f024dec58d6f48777
cp %{_builddir}/irrlicht-1.8.4/doc/jpglib-license.txt %{buildroot}/usr/share/package-licenses/irrlicht/042c2d15bbb2ea50e91497a2efdecb91fb420fad
cp %{_builddir}/irrlicht-1.8.4/doc/libpng-license.txt %{buildroot}/usr/share/package-licenses/irrlicht/97b8284aa8384d431f7fb5d3f282cc5c40840a4f
cp %{_builddir}/irrlicht-1.8.4/source/Irrlicht/bzip2/LICENSE %{buildroot}/usr/share/package-licenses/irrlicht/1c0c6888759a63c32bca7eb63353af2cd9bd5d9e
cp %{_builddir}/irrlicht-1.8.4/source/Irrlicht/libpng/LICENSE %{buildroot}/usr/share/package-licenses/irrlicht/9d3864488f66fd0af3286cd5430635ad2385f7bc
pushd source/Irrlicht
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/irrlicht/CDynamicMeshBuffer.h
/usr/include/irrlicht/CIndexBuffer.h
/usr/include/irrlicht/CMeshBuffer.h
/usr/include/irrlicht/CVertexBuffer.h
/usr/include/irrlicht/EAttributes.h
/usr/include/irrlicht/ECullingTypes.h
/usr/include/irrlicht/EDebugSceneTypes.h
/usr/include/irrlicht/EDeviceTypes.h
/usr/include/irrlicht/EDriverFeatures.h
/usr/include/irrlicht/EDriverTypes.h
/usr/include/irrlicht/EGUIAlignment.h
/usr/include/irrlicht/EGUIElementTypes.h
/usr/include/irrlicht/EHardwareBufferFlags.h
/usr/include/irrlicht/EMaterialFlags.h
/usr/include/irrlicht/EMaterialTypes.h
/usr/include/irrlicht/EMeshWriterEnums.h
/usr/include/irrlicht/EMessageBoxFlags.h
/usr/include/irrlicht/EPrimitiveTypes.h
/usr/include/irrlicht/ESceneNodeAnimatorTypes.h
/usr/include/irrlicht/ESceneNodeTypes.h
/usr/include/irrlicht/EShaderTypes.h
/usr/include/irrlicht/ETerrainElements.h
/usr/include/irrlicht/IAnimatedMesh.h
/usr/include/irrlicht/IAnimatedMeshMD2.h
/usr/include/irrlicht/IAnimatedMeshMD3.h
/usr/include/irrlicht/IAnimatedMeshSceneNode.h
/usr/include/irrlicht/IAttributeExchangingObject.h
/usr/include/irrlicht/IAttributes.h
/usr/include/irrlicht/IBillboardSceneNode.h
/usr/include/irrlicht/IBillboardTextSceneNode.h
/usr/include/irrlicht/IBoneSceneNode.h
/usr/include/irrlicht/ICameraSceneNode.h
/usr/include/irrlicht/IColladaMeshWriter.h
/usr/include/irrlicht/ICursorControl.h
/usr/include/irrlicht/IDummyTransformationSceneNode.h
/usr/include/irrlicht/IDynamicMeshBuffer.h
/usr/include/irrlicht/IEventReceiver.h
/usr/include/irrlicht/IFileArchive.h
/usr/include/irrlicht/IFileList.h
/usr/include/irrlicht/IFileSystem.h
/usr/include/irrlicht/IGPUProgrammingServices.h
/usr/include/irrlicht/IGUIButton.h
/usr/include/irrlicht/IGUICheckBox.h
/usr/include/irrlicht/IGUIColorSelectDialog.h
/usr/include/irrlicht/IGUIComboBox.h
/usr/include/irrlicht/IGUIContextMenu.h
/usr/include/irrlicht/IGUIEditBox.h
/usr/include/irrlicht/IGUIElement.h
/usr/include/irrlicht/IGUIElementFactory.h
/usr/include/irrlicht/IGUIEnvironment.h
/usr/include/irrlicht/IGUIFileOpenDialog.h
/usr/include/irrlicht/IGUIFont.h
/usr/include/irrlicht/IGUIFontBitmap.h
/usr/include/irrlicht/IGUIImage.h
/usr/include/irrlicht/IGUIImageList.h
/usr/include/irrlicht/IGUIInOutFader.h
/usr/include/irrlicht/IGUIListBox.h
/usr/include/irrlicht/IGUIMeshViewer.h
/usr/include/irrlicht/IGUIScrollBar.h
/usr/include/irrlicht/IGUISkin.h
/usr/include/irrlicht/IGUISpinBox.h
/usr/include/irrlicht/IGUISpriteBank.h
/usr/include/irrlicht/IGUIStaticText.h
/usr/include/irrlicht/IGUITabControl.h
/usr/include/irrlicht/IGUITable.h
/usr/include/irrlicht/IGUIToolbar.h
/usr/include/irrlicht/IGUITreeView.h
/usr/include/irrlicht/IGUIWindow.h
/usr/include/irrlicht/IGeometryCreator.h
/usr/include/irrlicht/IImage.h
/usr/include/irrlicht/IImageLoader.h
/usr/include/irrlicht/IImageWriter.h
/usr/include/irrlicht/IIndexBuffer.h
/usr/include/irrlicht/ILightManager.h
/usr/include/irrlicht/ILightSceneNode.h
/usr/include/irrlicht/ILogger.h
/usr/include/irrlicht/IMaterialRenderer.h
/usr/include/irrlicht/IMaterialRendererServices.h
/usr/include/irrlicht/IMesh.h
/usr/include/irrlicht/IMeshBuffer.h
/usr/include/irrlicht/IMeshCache.h
/usr/include/irrlicht/IMeshLoader.h
/usr/include/irrlicht/IMeshManipulator.h
/usr/include/irrlicht/IMeshSceneNode.h
/usr/include/irrlicht/IMeshWriter.h
/usr/include/irrlicht/IMetaTriangleSelector.h
/usr/include/irrlicht/IOSOperator.h
/usr/include/irrlicht/IParticleAffector.h
/usr/include/irrlicht/IParticleAnimatedMeshSceneNodeEmitter.h
/usr/include/irrlicht/IParticleAttractionAffector.h
/usr/include/irrlicht/IParticleBoxEmitter.h
/usr/include/irrlicht/IParticleCylinderEmitter.h
/usr/include/irrlicht/IParticleEmitter.h
/usr/include/irrlicht/IParticleFadeOutAffector.h
/usr/include/irrlicht/IParticleGravityAffector.h
/usr/include/irrlicht/IParticleMeshEmitter.h
/usr/include/irrlicht/IParticleRingEmitter.h
/usr/include/irrlicht/IParticleRotationAffector.h
/usr/include/irrlicht/IParticleSphereEmitter.h
/usr/include/irrlicht/IParticleSystemSceneNode.h
/usr/include/irrlicht/IQ3LevelMesh.h
/usr/include/irrlicht/IQ3Shader.h
/usr/include/irrlicht/IRandomizer.h
/usr/include/irrlicht/IReadFile.h
/usr/include/irrlicht/IReferenceCounted.h
/usr/include/irrlicht/ISceneCollisionManager.h
/usr/include/irrlicht/ISceneLoader.h
/usr/include/irrlicht/ISceneManager.h
/usr/include/irrlicht/ISceneNode.h
/usr/include/irrlicht/ISceneNodeAnimator.h
/usr/include/irrlicht/ISceneNodeAnimatorCameraFPS.h
/usr/include/irrlicht/ISceneNodeAnimatorCameraMaya.h
/usr/include/irrlicht/ISceneNodeAnimatorCollisionResponse.h
/usr/include/irrlicht/ISceneNodeAnimatorFactory.h
/usr/include/irrlicht/ISceneNodeFactory.h
/usr/include/irrlicht/ISceneUserDataSerializer.h
/usr/include/irrlicht/IShaderConstantSetCallBack.h
/usr/include/irrlicht/IShadowVolumeSceneNode.h
/usr/include/irrlicht/ISkinnedMesh.h
/usr/include/irrlicht/ITerrainSceneNode.h
/usr/include/irrlicht/ITextSceneNode.h
/usr/include/irrlicht/ITexture.h
/usr/include/irrlicht/ITimer.h
/usr/include/irrlicht/ITriangleSelector.h
/usr/include/irrlicht/IVertexBuffer.h
/usr/include/irrlicht/IVideoDriver.h
/usr/include/irrlicht/IVideoModeList.h
/usr/include/irrlicht/IVolumeLightSceneNode.h
/usr/include/irrlicht/IWriteFile.h
/usr/include/irrlicht/IXMLReader.h
/usr/include/irrlicht/IXMLWriter.h
/usr/include/irrlicht/IrrCompileConfig.h
/usr/include/irrlicht/IrrlichtDevice.h
/usr/include/irrlicht/Keycodes.h
/usr/include/irrlicht/S3DVertex.h
/usr/include/irrlicht/SAnimatedMesh.h
/usr/include/irrlicht/SColor.h
/usr/include/irrlicht/SExposedVideoData.h
/usr/include/irrlicht/SIrrCreationParameters.h
/usr/include/irrlicht/SKeyMap.h
/usr/include/irrlicht/SLight.h
/usr/include/irrlicht/SMaterial.h
/usr/include/irrlicht/SMaterialLayer.h
/usr/include/irrlicht/SMesh.h
/usr/include/irrlicht/SMeshBuffer.h
/usr/include/irrlicht/SMeshBufferLightMap.h
/usr/include/irrlicht/SMeshBufferTangents.h
/usr/include/irrlicht/SParticle.h
/usr/include/irrlicht/SSharedMeshBuffer.h
/usr/include/irrlicht/SSkinMeshBuffer.h
/usr/include/irrlicht/SVertexIndex.h
/usr/include/irrlicht/SVertexManipulator.h
/usr/include/irrlicht/SViewFrustum.h
/usr/include/irrlicht/SceneParameters.h
/usr/include/irrlicht/aabbox3d.h
/usr/include/irrlicht/coreutil.h
/usr/include/irrlicht/dimension2d.h
/usr/include/irrlicht/driverChoice.h
/usr/include/irrlicht/fast_atof.h
/usr/include/irrlicht/heapsort.h
/usr/include/irrlicht/irrAllocator.h
/usr/include/irrlicht/irrArray.h
/usr/include/irrlicht/irrList.h
/usr/include/irrlicht/irrMap.h
/usr/include/irrlicht/irrMath.h
/usr/include/irrlicht/irrString.h
/usr/include/irrlicht/irrTypes.h
/usr/include/irrlicht/irrXML.h
/usr/include/irrlicht/irrlicht.h
/usr/include/irrlicht/irrpack.h
/usr/include/irrlicht/irrunpack.h
/usr/include/irrlicht/line2d.h
/usr/include/irrlicht/line3d.h
/usr/include/irrlicht/matrix4.h
/usr/include/irrlicht/path.h
/usr/include/irrlicht/plane3d.h
/usr/include/irrlicht/position2d.h
/usr/include/irrlicht/quaternion.h
/usr/include/irrlicht/rect.h
/usr/include/irrlicht/triangle3d.h
/usr/include/irrlicht/vector2d.h
/usr/include/irrlicht/vector3d.h
/usr/lib64/libIrrlicht.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libIrrlicht.so.1.8
/usr/lib64/libIrrlicht.so.1.8.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/irrlicht/042c2d15bbb2ea50e91497a2efdecb91fb420fad
/usr/share/package-licenses/irrlicht/1c0c6888759a63c32bca7eb63353af2cd9bd5d9e
/usr/share/package-licenses/irrlicht/97b8284aa8384d431f7fb5d3f282cc5c40840a4f
/usr/share/package-licenses/irrlicht/9d3864488f66fd0af3286cd5430635ad2385f7bc
/usr/share/package-licenses/irrlicht/bcbd5fcde0d5d5a7a0e6729f024dec58d6f48777
/usr/share/package-licenses/irrlicht/d964dbe91cbf7511e4f1857db9e99fdaf6658055
